name: qrreadmeapp
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  qrcode_reader: ^0.4.4
  sqflite: ^1.1.7+3
  path_provider: ^0.5.0+1
  url_launcher: ^5.2.7
  flutter_map: ^0.5.0+1
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:


  uses-material-design: true
